name: Print File Path

on: [push]

jobs:
  print-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print file path
        run: echo "File path: /c:/DUANHTML/INDEX.HTML"
